### ISSUE TITLE
Request: how to export coordinates of brain regions from transformed atlas images

### ISSUE THREAD

**Issue by marinafridman** [leuat/nutil#129]
Hi,

I would like to use the transformed atlas maps to quantify fluorescence in some histological images. QuickNII did a great job of creating transformed maps from the Allen Atlas to match my coronal sections. Now I was wondering how I can go about getting the coordinates of specific brain regions in the transformed atlas images. Would it would be possible for the QuickNII software to produce a look up table of regions and coordinates for the transformed Atlas maps? Or is this information already present in the current output? 

Alternatively if you wouldn't mind to share some code for how to convert the atlas images using the anchoring values, that would also be a big help!

Many thanks!
~Marina

**Comment by leuat** [comment]
Not entirely sure what you're asking for here, but if you're talking about mapping the 2D segmented areas to a list of 3D output data - it is already implemented! QuickNII outputs a transformation matrix in the anchored xml file that provides the information for reverse transformation.

![3D](https://user-images.githubusercontent.com/5620670/83003598-d3b40c80-a00e-11ea-9d3e-202780de2fe8.png)

In order to get the 3D point cloud from Nutil, you need to : 
a) Use a custom region list (will be colour coded in the json output)
b) Turn on the "Coordinate extraction" under the "advanced" settings
c) After having run the analysis, the 3D points are stored in the "Coordinates/" directory, both as individual slices and as a combined segments
d) View the 3D point cloud using Meshview : https://www.nesys.uio.no/MeshView/

**Comment by Majpuc** [comment]
Dear Marina,
In order to quantify your labelling, you'll have to use the QUINT workflow. https://www.frontiersin.org/articles/10.3389/fninf.2019.00075/full
Maybe that is what you did already? As mentionned above, Nutil Quantifier will give output as Tables of your object coordinates as well as a coordinate file allowing you to visualize your objects in 3D. Let me know if you have questions about this, we can arrange a small video call.
Best, Maja

**Comment by marinafridman** [comment]
Thank you for the quick replies!

Sorry for not explaining very well. My objective is to get one value of overall fluorescence (not cell count) per defined brain region. I'm not using the segmentation protocol; instead, I want to overlay a brain region mask from the QuickNII transformed atlas on my fluorescence image. 

What I'm unsure about is how to get this mask. Since I am not doing cell detection, I don't have any "objects" for which to get coordinates. Would it be possible to get the coordinates of the brain regions themselves to make a mask? Is this what you meant @leuat by using a custom region list? Will the coordinate list include custom brain regions?

Thanks again!

**Comment by Majpuc** [comment]
Hi,
After you've anchored your images with QuickNII, you can export your customised atlas maps in QuickNII using the button"export slices". By overlaying this customized mask with your image in i.e. Photoshop, you will be able to see whether the labelling present on your image occupies partially or totally a brain region. However, in order to get an overall value of how much of a brain region your fluorescence label is occupying, you need to segment this fluorescence label. This is easily done using Fiji or ilastik. I assume you have 2D image data..

**Comment by marinafridman** [comment]
Hi Maya,
I believe with the "export slices" option in QuickNII, you cannot specify custom regions as you can in Nutil, and the automatic ones they provide do not offer the resolution I need (to be more specific, I am looking for masks for individual visual cortical areas, but in the exported slices all visual areas are clumped together). Is that correct?

I followed your suggestion and did a segmentation with ImageJ. Now I would like to run the quantifier in Nutil, but I am getting an error. If you have any insights I would appreciate it!
```
Wed May 27 14:06:07 2020 : Error: You need to specify at least one input file. Press the help button for instructions. 
```
The files in quantifier_input_dir are 8-bit PNG files. Is that why they aren't being detected?
Here are my settings for the Quantifier:
```
type = Quantifier
name = 
analysis_type = QUINT
quantifier_input_dir = E:/quietFB/histomagic/seg
quantifier_atlas_dir = E:/quietFB/histomagic/DAPI/visuAlign
label_file = Allen Mouse Brain 2015
xml_anchor_file = E:/quietFB/histomagic/DAPI/anchoring_aftervisualign.xml
quantifier_output_dir = E:/quietFB/histomagic
output_report = All
extraction_color = 170,170,255,255
object_splitting = Yes
object_min_size = 1
object_max_size = 100000
global_pixel_scale = 1
quantifier_pixel_scale_unit = pixels
use_custom_masks = No
custom_mask_color = 255,255,255,255
output_report_type = CSV
custom_region_type = Custom
custom_region_file = C:/Users/Marina/Documents/Nutil_v0402/Nutil_v0402/CustomRegion/CustomRegionVis.xlsx
coordinate_extraction = All
pixel_density = 1
nifti_size = 0
pattern_match = _sXXX
files = 
```
Thanks again for all your help!

**Comment by Majpuc** [comment]
Hi Marina,
The exported QuickNII maps should show the cortical layers, it is strange if you don't get that. The cortical layers have a slight difference in color but should be visble. 
For the error message in Nutil, it could be that your files are not named according to the pattern _sxxx and therefore not recognized. You can also chose the regex naming in Nutil, select user in pattern match. Do your segmentation files and atlas files have the same names?

**Comment by marinafridman** [comment]
Error messages in Nutil are fixed, thank you :)
For QuickNII: I was looking at the _nl maps, but now looking at the Rainbow maps, I do see segmentation by layer.

Thanks so much for all your help!

**Comment by marinafridman** [comment]
Hello, 
I have one more question/request :) For the QuickNII exported maps, would it be possible to have differentiation within the thalamus as well? It seems some areas eg LGd (area 170) are already differentiated, but others like LP (area 218) are not.
Many thanks.

**Comment by Majpuc** [comment]
Hi,
QuickNII is using the resources provided by the Allen Institute to generate the maps. What you describe is correct and even in the CCFv3, 2017 version, this area 128 is not further sub-delineated. So unfortunately, we don't have other atlases for the mouse. One solution for you could be to use a dataset My colleague Ingvild Bjerke shared via EBRAINS (https://kg.ebrains.eu/search/?facet_type[0]=Dataset&q=co-registration#Dataset/ebddb858-708c-4ea8-b04a-3fe26978f7d7). You will find there the xml of another registered atlas, you could use to find boundaries between your regions of interest. Please contact us through support@ebrains.eu if you experience problems or have questions.
Best, Maja
